django_todo_list/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from todo import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tasks/', views.home, name='main_page'),
    url(r'^add/', views.add, name='add'),
    url(r'^update/(?P<id>\d+)/$', views.update, name='update'),
    url(r'^delete/(?P<id>\d+)/$', views.delete, name='delete'),
    url(r'^complete/(?P<id>\d+)/$', views.task_complete, name='task-complete'),
    url(r'^search/$', views.search, name='search'),
    url(r'^$', views.login, name='login'),
    url(r'^sign_in/', views.sign_in, name='sign_in'),
    url(r'^logout/$', views.sign_out, name='sign_out')
]

todo/models.py
from django.db import models

# Create your models here.

class Color(models.Model):
    code = models.CharField(max_length=20, verbose_name='ColorCode')
    color_title = models.CharField(max_length=20, verbose_name='Title')

    def __str__(self):
        return self.color_title

class User(models.Model):
    login = models.CharField(max_length=20, verbose_name='Login')
    password = models.CharField(max_length=20, verbose_name='Password')

    def __str__(self):
        return self.login

class Task(models.Model):
    title = models.CharField(max_length=50, verbose_name='Task')
    description = models.TextField(verbose_name='Description')
    date = models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')
    is_done = models.BooleanField(default=False, verbose_name='Done')
    color = models.ForeignKey(Color,null=True, on_delete=models.CASCADE, verbose_name='Color')
    user = models.ForeignKey(User,null=True, on_delete=models.CASCADE, verbose_name='User')

    class Meta:
        verbose_name='Task'
        verbose_name_plural='Tasks'

    def __str__(self):
        return self.title

todo/forms.py
from django import forms
from todo.models import Task
from todo.models import Color
from todo.models import User

class TaskForm(forms.ModelForm):
    color = forms.ModelChoiceField(queryset=Color.objects)
    user = forms.ModelChoiceField(queryset=User.objects)
    class Meta:
        model = Task
        fields = ('title', 'description', 'color', 'user')

todo/views.py
from django.shortcuts import render, redirect
from todo.models import Task
from todo.forms import TaskForm
from todo.models import Color
from todo.models import User


def home(request):
    user_id = request.session['user_id']
    tasks = Task.objects.filter(user_id=user_id).order_by('is_done')
    return render(request, 'index.html', {'tasks': tasks})

def add(request):
    colors = Color.objects.all()
    form = TaskForm(request.POST or None)
    form_title = "Create Task"
    user_id = request.session['user_id']
    if form.is_valid():
        form.save()
        return redirect('/tasks')
    return render(request, 'task-form.html', {'form': form,
                                              'colors': colors,
                                              'form_title': form_title,
                                              'user_id': user_id})

def update(request, id):
    colors = Color.objects.all()
    task = Task.objects.get(id=id)
    form = TaskForm(request.POST or None, instance=task)
    form_title = "Edit Task"
    user_id = request.session['user_id']
    if form.is_valid():
        form.save()
        return redirect('/tasks')
    return render(request, 'task-form.html', {'form': form,
                                              'task': task,
                                              'colors': colors,
                                              'form_title': form_title,
                                              'user_id': user_id})

def delete(request, id):
    task = Task.objects.get(id=id)
    task.delete()
    return redirect('/tasks')

def task_complete(request, id):
    is_done = not Task.objects.get(id=id).is_done
    Task.objects.filter(id=id).update(is_done=is_done)
    return redirect('/tasks')

def search(request):
    query = request.GET.get('title')
    user_id = request.session['user_id']
    tasks = Task.objects.filter(title__contains=query, user_id=user_id)
    return render(request, 'index.html', {'tasks': tasks})

def login(request):
    return render(request, 'login.html')

def sign_in(request):
    login = request.GET.get('login')
    password = request.GET.get('password')
    if User.objects.filter(login=login).exists():
        user = User.objects.get(login=login)
        if user.password == password:
            request.session['user_id'] = user.id
            return redirect('/tasks')
    return redirect('/')

def sign_out(request):
    return redirect('/')

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TODO List</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
{% block page %}
{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block page %}
    <div class="main-content">
        <div class="header">
            <p class="header__title">Tasks Board</p>
            <a href="{% url 'add' %}" class="button add-button">Create task</a>
            <form method="get" action="{% url 'search' %}">
                <div class="search-form">
                        <input type="search" name="title" class="search">
                        <button class="search-button">Search</button>
                </div>
            </form>
            <a href="{% url 'sign_out' %}" class="button remove-button logout">Log out</a>
        </div>
        <div class="tasks-container">
            {% for task in tasks %}
            <div class="task-content">
                <div class="task-item" style="border-top: 6px solid {{ task.color.code }}">
                    {% if not task.is_done %}
                    <p class="task-item__title">{{ task.title }}</p>
                    <p class="task-item__description">{{ task.description }}</p>
                    <div class="task-item__buttons">
                        <a href="{% url 'update' task.id %}" class="button update-button"><i class="fas fa-edit"></i></a>
                        <a href="{% url 'delete' task.id %}" class="button remove-button"><i class="fas fa-trash-alt"></i></a>
                        <a href="{% url 'task-complete' task.id %}" class="button done-button">Done</a>
                    </div>
                    {% endif %}
                    {% if task.is_done %}
                        <p class="task-item__title done-task">{{ task.title }}</p>
                        <p class="task-item__description done-task">{{ task.description }}</p>
                        <div class="task-item__buttons">
                            <a href="{% url 'update' task.id %}" class="button update-button"><i class="fas fa-edit"></i></a>
                            <a href="{% url 'delete' task.id %}" class="button remove-button"><i class="fas fa-trash-alt"></i></a>
                            <a href="{% url 'task-complete' task.id %}" class="button undone-button">Undone</a>
                        </div>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block page %}
    <div class="form-login">
        <h2 class="form-title">Login</h2>
        <form method="get" class="add-form" action="{% url 'sign_in' %}">
            <div class="form-group">
                <input type="text" class="form-control input-title" name="login" id="login" placeholder="Login"
                       required>
            </div>
            <div class="form-group">
                <input type="password" class="form-control input-title" name="password" id="password"
                       placeholder="Password" required>
            </div>
          <button type="submit" class="submit-button">Sign In</button>
        </form>
    </div>
{% endblock %}

templates/task-form.html
{% extends 'base.html' %}
{% block page %}
    <div class="input-form">
        <h2 class="form-title">{{ form_title }}</h2>
        <form method="post" class="add-form">
        {% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control input-title" name="title" value="{{ task.title }}" id="title" placeholder="Title"
                       required>
            </div>
            <div class="form-group">
                <textarea class="form-control input-description" name="description"
                          id="description" placeholder="Description" required>{{ task.description }}</textarea>
            </div>
            <div class="form-group input-colors">
                <select name="color" required id="id_color">
                    <option value="" disabled {% ifequal task None %}selected{% endifequal %}>Choose color</option>
                    {% for color in colors %}
                        <option value="{{ color.id }}"
                                {% ifequal task.color_id color.id %}selected{% endifequal %}>{{ color.color_title }}</option>
                    {% endfor %}
                </select>
            </div>

            <select name="user" required id="id_user" style="display: none">
                <option value="{{ user_id }}" selected>{{ user_id }}</option>
            </select>

          <button type="submit" class="submit-button">Submit</button>
        </form>
    </div>
{% endblock %}

templates/test.html
{% extends 'base.html' %}
{% block page %}
    <div class="input-form">
        <h2 class="form-title">{% block title %}Edit Task{% endblock %}</h2>
        <form method="post" class="add-form">
        {% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control input-title" name="title" value="{{ task.title }}" id="title" placeholder="Title"
                       required>
            </div>
            <div class="form-group">
                <textarea class="form-control input-description" name="description"
                          id="description" placeholder="Description" required>{{ task.description }}</textarea>
            </div>
          <button type="submit" class="submit-button">Submit</button>
        </form>
    </div>
{% endblock %}